### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by nbuonin** [NYC-Camp/nyc-camp-2015#26]
I've been trying to test the scheduler for a few days and I can't get it to work.  On /admin/conference/events/1/schedule
I drag in a session into an open time slot (in this case, it's March 21), and it gets stuck.

I checked drush ws and saw this error message: 
EntityMetadataWrapperException: Unknown data property field_timeslot_allowed_types. in
EntityStructureWrapper->getPropertyInfo() (line 335 of /srv/bindings/543dee9170fc4484be0f3f977a3a3bb6/code/profiles/cod/modules/contrib/entity/includes/entity.wrapper.inc)

On my local site, I pasted in dpm(debug_backtrace()) on line 335, and the devel module prints out all the functions that are being called, but I don't know enough to figure it out from there.

I also tried adding field_timeslot_allowed_types to the "rooms" and "times" entities in the Conference menu, as they weren't there by default.  I flushed the cache and ran cron, and that didn't work either.

**Comment by timhobert** [comment]
COD has been updated from beta5 to beta6 on dev [ dev-nyc-camp-2015.gotpantheon.com ].
