### ISSUE TITLE
Session Submissions

### ISSUE THREAD

**Issue by nbuonin** [NYC-Camp/nyc-camp-2015#28]
**Issue**
We need to provide a way for a registered site user to propose sessions.  Once a session is proposed, a workflow will be triggered for admins to review sessions.

**Proposed Approach**
The proposed workflow is:
* Authenticated site user submits a proposed session 
  * This user may be different from presenter
    * use entity reference to select presenter (this means that the presenter must already be a site user,    does this blow up this workflow?)
  * email to confirmation to submitter (and presenter?)
* Session goes into a proposed sessions queue
  * publicly available
* Admins approve/disapprove
  * use a taxonomy to denote the state of a session
  * email sent either way
* Admin dashboard - views filtered on taxonomies
  * proposed
  * approved
  * declined
* Admin publishes approved sessions

**Comment by willykaram** [comment]
This is complete for now. The implementation could be better, but it's sufficient and we're not accepting session for this year anymore.
