### ISSUE TITLE
Social Sharing

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/nyc-camp-2015#51]
We need to implement Social Sharing of content. I would suggest that we just use the AddThis module (https://www.drupal.org/project/addthis), which is free and allows to theme the social icons to match our color scheme/brand identity. However, perhaps we can discuss in the comments to determine a different approach if needed.

**Comment by nbuonin** [comment]
I've got this merged into dev, and configured on the News CT.  We just need some theming on the buttons.

**Comment by willykaram** [comment]
Sweet, thanks Nick. I used that config to add the social buttons/fields to the other content types too. For now I've re-enabled the standard buttons/css from AddThis, and we can add some custom theming later once time permits. I'll add another issue for that.
