### ISSUE TITLE
Drupal Planet RSS Setup

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/nyc-camp-2015#67]
Reviewing the RSS feed setup for Drupal Planet and confirming that the Feed is working/connected to Planet.

**Comment by willykaram** [comment]
Moving this to next week's milestone as it's not absolutely essential for launch and initial partnership drive (although we can try to get it in if possible).

**Comment by nbuonin** [comment]
I created this view and registered with the Planet Drupal team: https://www.drupal.org/node/2530422#comment-10106518
