### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/nyc-camp-2015#69]
We need to configure our analytics tools, including Google Analytics. We can setup others if people suggest them.

**Comment by timhobert** [comment]
What's the GA UA-XXXXXX number? (Set up here: http://dev-nyc-camp-2015.gotpantheon.com/admin/config/system/googleanalytics )

**Comment by willykaram** [comment]
I just pulled it from the 2014 site and inputted it.

**Comment by willykaram** [comment]
I think for now that should suffice, unless we want to change strategy.

**Comment by willykaram** [comment]
I've removed the Chartbeat element from this issue and will setup a new issue for this.
